### ISSUE TITLE
ReadMe.md references "SparkFun ESP32 Thing" -- NOT "SAMD51 Thing Plus"

### ISSUE THREAD

**Issue by VashJuan** [sparkfun/SAMD51_Thing_Plus#3]
Is "SAMD51 Thing Plus" just a small modification of the ESP32 Thing, or ????

**Comment by bboyho** [comment]
Hi, I just noticed your question when viewing some files in this repo.

I'm not sure where you are seeing the references to the ESP32 in the README.MD? The Thing and Thing Plus are just different form factors. I assume that the original engineer used the Thing footprint as a template to start before adjusting the design for the Thing Plus footprint. Both boards have different features depending on the microcontroller that is populated (two of the major differences: one is that the ESP32 can connect to the cloud via WiFi while the SAMD51 cannot; the SAMD51 also does not need a USB-to-serial converter to upload new code since it has a native USB) and the pin locations are different.
